"use client";

/**
 * Liquid Glass primitives — the material system of the Liquid World.
 *
 * Every surface in WithIn speaks this language. The material is layered:
 * tint level (0–4) + backdrop blur/saturation + edge-light (a border made
 * of light, not strokes) + internal sheen + depth shadow. Components
 * differ by level and geometry, never by ad-hoc styling.
 */

import { forwardRef, type CSSProperties, type ReactNode } from "react";

export type LiquidLevel = 0 | 1 | 2 | 3 | 4;

type BaseProps = {
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
  /** Material depth level — 0 environmental → 4 modal */
  level?: LiquidLevel;
  /** Draw the edge-light ring (border generated by light) */
  edge?: boolean;
  /** Draw the internal specular sheen */
  sheen?: boolean;
  /** Refraction light swimming inside the surface */
  refract?: boolean;
  /** Hover lift + press displacement */
  press?: boolean;
  /** Liquid focus illumination (auto for controls) */
  focus?: boolean;
  onClick?: () => void;
  id?: string;
  role?: string;
  "aria-label"?: string;
};

export function liquidClasses(level: LiquidLevel, opts: {
  edge?: boolean;
  sheen?: boolean;
  press?: boolean;
  shadow?: boolean;
} = {}): string {
  const cls = ["liquid-" + level];
  if (opts.edge !== false) cls.push("liquid-edge");
  if (opts.sheen) cls.push("liquid-sheen");
  if (opts.press) cls.push("liquid-press");
  if (opts.shadow !== false) cls.push(`liquid-shadow-${level}`);
  return cls.join(" ");
}

/** Render the optional refraction light child. */
export function RefractLight({ on }: { on: boolean }) {
  if (!on) return null;
  return <span aria-hidden className="liquid-refract-light" />;
}

/* ── LiquidSurface — the atom every other primitive composes ───────── */
export const LiquidSurface = forwardRef<HTMLDivElement, BaseProps>(
  function LiquidSurface(
    { children, className = "", style, level = 1, edge = true, sheen = false, refract = false, press = false, focus = false, onClick, id, role, "aria-label": ariaLabel },
    ref
  ) {
    const cls = [
      liquidClasses(level, { edge, sheen, press }),
      refract ? "liquid-refract" : "",
      focus ? "liquid-focus" : "",
      "rounded-3xl",
      className,
    ].filter(Boolean).join(" ");
    return (
      <div ref={ref} className={cls} style={style} onClick={onClick} id={id} role={role} aria-label={ariaLabel}>
        <RefractLight on={refract} />
        {children}
      </div>
    );
  }
);

/* ── LiquidPanel — a soft translucent interface layer (L1–L2) ──────── */
export function LiquidPanel({ children, className = "", level = 1, sheen = true, refract = false, style, "aria-label": ariaLabel }: BaseProps) {
  return (
    <LiquidSurface level={level} edge sheen={sheen} refract={refract} className={className} style={style} aria-label={ariaLabel}>
      {children}
    </LiquidSurface>
  );
}

/* ── LiquidButton — interactive surface (L2), pressable ─────────────── */
type ButtonProps = BaseProps & {
  variant?: "primary" | "ghost" | "outline";
  size?: "sm" | "md" | "lg";
  href?: string;
  type?: "button" | "submit";
  disabled?: boolean;
  target?: string;
  rel?: string;
};

const BTN_SIZES = {
  sm: "px-4 py-2 text-[12px]",
  md: "px-5 py-2.5 text-[13px]",
  lg: "px-7 py-3 text-sm",
};

export const LiquidButton = forwardRef<HTMLButtonElement, ButtonProps>(
  function LiquidButton(
    { children, className = "", variant = "ghost", size = "md", href, type = "button", disabled, target, rel, onClick, "aria-label": ariaLabel },
    ref
  ) {
    const base = [
      "inline-flex items-center justify-center gap-2 rounded-full font-semibold liquid-press liquid-focus transition-colors",
      BTN_SIZES[size],
      disabled ? "opacity-40 pointer-events-none" : "",
      className,
    ].filter(Boolean).join(" ");

    const inner = (
      <>
        {variant === "primary" && (
          <span
            aria-hidden
            className="pointer-events-none absolute inset-0 rounded-full"
            style={{
              background: "linear-gradient(135deg, rgba(var(--mood-rgb),0.85), rgba(var(--mood-rgb),0.55))",
              boxShadow: "0 0 24px rgba(var(--mood-rgb),0.35), inset 0 1px 0 rgba(255,255,255,0.35)",
            }}
          />
        )}
        {variant === "ghost" && <span aria-hidden className="liquid-edge pointer-events-none absolute inset-0 rounded-full" />}
        {variant === "outline" && <span aria-hidden className="pointer-events-none absolute inset-0 rounded-full border border-white/15 bg-white/[0.04]" />}
        <span className="relative z-[2] inline-flex items-center gap-2">{children}</span>
      </>
    );

    if (href) {
      return (
        <a href={href} target={target} rel={rel} className={`relative inline-flex ${base}`} onClick={onClick} aria-label={ariaLabel}>
          {inner}
        </a>
      );
    }
    return (
      <button ref={ref} type={type} disabled={disabled} className={`relative ${base}`} onClick={onClick} aria-label={ariaLabel}>
        {inner}
      </button>
    );
  }
);

/* ── LiquidTab — floating liquid tab control ────────────────────────── */
export function LiquidTab({
  active,
  children,
  onClick,
  className = "",
}: {
  active: boolean;
  children: ReactNode;
  onClick: () => void;
  className?: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={active}
      className={`relative rounded-full px-4 py-2 text-[12.5px] font-medium liquid-press liquid-focus transition-colors ${
        active ? "text-white" : "text-gray-400 hover:text-gray-100"
      } ${className}`}
    >
      {active && (
        <span
          aria-hidden
          className="absolute inset-0 rounded-full"
          style={{
            background: "rgba(var(--mood-rgb),0.16)",
            boxShadow: "inset 0 0 0 1px rgba(var(--mood-rgb),0.35), 0 4px 16px rgba(0,0,0,0.25)",
          }}
        />
      )}
      {!active && <span aria-hidden className="pointer-events-none absolute inset-0 rounded-full bg-white/[0.03]" />}
      <span className="relative z-[2]">{children}</span>
    </button>
  );
}

/* ── LiquidInput — tactile input surface (L2) ───────────────────────── */
export const LiquidInput = forwardRef<HTMLInputElement, {
  value?: string;
  defaultValue?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  onKeyDown?: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  placeholder?: string;
  type?: string;
  name?: string;
  required?: boolean;
  autoComplete?: string;
  "aria-label"?: string;
  className?: string;
}>(function LiquidInput({ className = "", ...rest }, ref) {
  return (
    <input
      ref={ref}
      {...rest}
      className={`w-full rounded-2xl bg-white/[0.04] px-4 py-3 text-sm text-white outline-none transition placeholder:text-gray-500 liquid-focus ${className}`}
      style={{
        boxShadow: "inset 0 1px 0 rgba(255,255,255,0.07), inset 0 0 0 1px rgba(255,255,255,0.09)",
      }}
    />
  );
});

/* ── LiquidPill — small atmospheric chip ────────────────────────────── */
export function LiquidPill({
  active,
  children,
  onClick,
  tint,
  className = "",
}: {
  active?: boolean;
  children: ReactNode;
  onClick?: () => void;
  tint?: string;
  className?: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={active}
      className={`relative overflow-hidden rounded-full liquid-press liquid-focus ${className}`}
      style={active && tint ? { background: tint, boxShadow: `0 4px 20px ${tint}` } : undefined}
    >
      {!active && (
        <span
          aria-hidden
          className="absolute inset-0"
          style={{ boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.09), inset 0 1px 0 rgba(255,255,255,0.06)" }}
        />
      )}
      <span className="relative z-[2]">{children}</span>
    </button>
  );
}

/* ── LiquidOverlay — modal foreground surface (L4) ──────────────────── */
export function LiquidOverlay({
  children,
  onClose,
  className = "",
  label,
}: {
  children: ReactNode;
  onClose: () => void;
  className?: string;
  label: string;
}) {
  return (
    <div className="fixed inset-0 z-[90] flex items-center justify-center p-4">
      <button type="button" aria-label={`Close ${label}`} onClick={onClose} className="absolute inset-0 cursor-default bg-black/65 backdrop-blur-md" />
      <div className={`relative liquid-4 liquid-edge liquid-sheen liquid-shadow-4 rounded-modal ${className}`}>{children}</div>
    </div>
  );
}
