"use client";

/**
 * Crystal primitives — the material system of the Crystal World.
 *
 * Surfaces REVEAL the world instead of covering it. Four transparency
 * levels (clear → soft → elevated → foreground), edge-light borders
 * generated by masked light, internal specular sheen, and depth shadows
 * tuned for light environments. Text colors come from the environment
 * tokens so readability survives transparency.
 */

import { forwardRef, type CSSProperties, type ReactNode } from "react";

export type CrystalLevel = "clear" | "soft" | "elevated" | "foreground";

type BaseProps = {
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
  /** Transparency level — clear reveals most, foreground reveals least */
  level?: CrystalLevel;
  /** Draw the edge-light ring */
  edge?: boolean;
  /** Draw the internal specular sheen */
  sheen?: boolean;
  /** Depth shadow: low | medium | high */
  depth?: "none" | "low" | "medium" | "high";
  /** Hover lift + press compression */
  press?: boolean;
  /** Crystal focus illumination (auto for controls) */
  focus?: boolean;
  onClick?: () => void;
  id?: string;
  role?: string;
  "aria-label"?: string;
};

export function crystalClasses(
  level: CrystalLevel,
  opts: { edge?: boolean; sheen?: boolean; press?: boolean; depth?: BaseProps["depth"] } = {}
): string {
  const cls = [`crystal-${level}`];
  if (opts.edge !== false) cls.push("crystal-edge");
  if (opts.sheen) cls.push("crystal-sheen");
  if (opts.press) cls.push("crystal-press");
  if (opts.depth && opts.depth !== "none") cls.push(`depth-${opts.depth}`);
  return cls.join(" ");
}

/** CrystalSurface — the atom every other crystal primitive composes. */
export const CrystalSurface = forwardRef<HTMLDivElement, BaseProps>(
  function CrystalSurface(
    {
      children,
      className = "",
      style,
      level = "soft",
      edge = true,
      sheen = true,
      depth = "low",
      press = false,
      focus = false,
      onClick,
      id,
      role,
      "aria-label": ariaLabel,
    },
    ref
  ) {
    const cls = [
      crystalClasses(level, { edge, sheen, press, depth }),
      focus ? "crystal-focus" : "",
      "rounded-3xl",
      className,
    ]
      .filter(Boolean)
      .join(" ");
    return (
      <div ref={ref} className={cls} style={style} onClick={onClick} id={id} role={role} aria-label={ariaLabel}>
        {children}
      </div>
    );
  }
);

/** CrystalPanel — the default interface layer (soft, readable). */
export function CrystalPanel({
  children,
  className = "",
  level = "soft",
  depth = "low",
  style,
  "aria-label": ariaLabel,
}: BaseProps) {
  return (
    <CrystalSurface level={level} depth={depth} className={className} style={style} aria-label={ariaLabel}>
      {children}
    </CrystalSurface>
  );
}

/** CrystalWindow — a mostly-clear surface the world shows through. */
export function CrystalWindow({ children, className = "", style, "aria-label": ariaLabel }: BaseProps) {
  return (
    <CrystalSurface level="clear" depth="none" sheen className={className} style={style} aria-label={ariaLabel}>
      {children}
    </CrystalSurface>
  );
}

/* ── CrystalButton — interactive crystal control ─────────────────────── */
type CrystalButtonProps = BaseProps & {
  variant?: "primary" | "glass" | "ghost";
  size?: "sm" | "md" | "lg";
  href?: string;
  type?: "button" | "submit";
  disabled?: boolean;
  target?: string;
  rel?: string;
};

const CRYSTAL_SIZES = {
  sm: "px-4 py-2 text-[12px]",
  md: "px-5 py-2.5 text-[13px]",
  lg: "px-7 py-3 text-sm",
};

export const CrystalButton = forwardRef<HTMLButtonElement, CrystalButtonProps>(
  function CrystalButton(
    {
      children,
      className = "",
      variant = "glass",
      size = "md",
      href,
      type = "button",
      disabled,
      target,
      rel,
      onClick,
      "aria-label": ariaLabel,
    },
    ref
  ) {
    const base = [
      "relative inline-flex items-center justify-center gap-2 rounded-full font-semibold crystal-press crystal-focus",
      CRYSTAL_SIZES[size],
      disabled ? "opacity-40 pointer-events-none" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    const inner = (
      <>
        {variant === "primary" && (
          <span
            aria-hidden
            className="pointer-events-none absolute inset-0 rounded-full"
            style={{
              background: "linear-gradient(135deg, rgba(var(--mood-rgb),0.92), rgba(var(--mood-rgb),0.7))",
              boxShadow: "0 4px 16px rgba(var(--mood-rgb),0.32), inset 0 1px 0 rgba(255,255,255,0.45)",
            }}
          />
        )}
        {variant === "glass" && (
          <span
            aria-hidden
            className="crystal-edge pointer-events-none absolute inset-0 rounded-full"
            style={{ background: "rgba(255,255,255,0.4)", backdropFilter: "blur(10px) saturate(1.4)", WebkitBackdropFilter: "blur(10px) saturate(1.4)" }}
          />
        )}
        {variant === "ghost" && (
          <span aria-hidden className="pointer-events-none absolute inset-0 rounded-full bg-white/[0.14]" />
        )}
        <span className={`relative z-[2] inline-flex items-center gap-2 ${variant === "primary" ? "text-white" : "text-[#232136]"}`}>
          {children}
        </span>
      </>
    );

    if (href) {
      return (
        <a href={href} target={target} rel={rel} className={base} onClick={onClick} aria-label={ariaLabel}>
          {inner}
        </a>
      );
    }
    return (
      <button ref={ref} type={type} disabled={disabled} className={base} onClick={onClick} aria-label={ariaLabel}>
        {inner}
      </button>
    );
  }
);

/* ── CrystalTab — floating crystal tab control ───────────────────────── */
export function CrystalTab({
  active,
  children,
  onClick,
  className = "",
}: {
  active: boolean;
  children: ReactNode;
  onClick: () => void;
  className?: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={active}
      className={`relative rounded-full px-4 py-2 text-[12.5px] font-medium crystal-press crystal-focus transition-colors ${
        active ? "text-white" : "text-[#5f5e74] hover:text-[#232136]"
      } ${className}`}
    >
      {active && (
        <span
          aria-hidden
          className="absolute inset-0 rounded-full"
          style={{
            background: "linear-gradient(135deg, rgba(var(--mood-rgb),0.9), rgba(var(--mood-rgb),0.68))",
            boxShadow: "0 4px 14px rgba(var(--mood-rgb),0.3), inset 0 1px 0 rgba(255,255,255,0.4)",
          }}
        />
      )}
      {!active && <span aria-hidden className="pointer-events-none absolute inset-0 rounded-full bg-white/[0.35]" />}
      <span className="relative z-[2]">{children}</span>
    </button>
  );
}

/* ── CrystalInput — clear crystal container for text ─────────────────── */
export const CrystalInput = forwardRef<HTMLInputElement, {
  value?: string;
  defaultValue?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  onKeyDown?: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  placeholder?: string;
  type?: string;
  name?: string;
  required?: boolean;
  autoComplete?: string;
  "aria-label"?: string;
  className?: string;
}>(function CrystalInput({ className = "", ...rest }, ref) {
  return (
    <input
      ref={ref}
      {...rest}
      className={`crystal-focus w-full rounded-2xl bg-white/[0.55] px-4 py-3 text-sm text-[#232136] outline-none transition placeholder:text-[#8b8aa0] ${className}`}
      style={{ boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.7), inset 0 1px 0 rgba(255,255,255,0.9), var(--depth-low)" }}
    />
  );
});

/** Muted text token — use inside crystal surfaces for meta/labels. */
export function CrystalMeta({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <span className={`text-[#5f5e74] ${className}`}>{children}</span>;
}
